# Generated by Django 5.2.6 on 2025-10-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(default='00000000', max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_mvp', models.BooleanField(default=True)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
