# Generated by Django 5.2.6 on 2025-10-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='30000000', max_length=20),
        ),
    ]
